# https://docs.travis-ci.com/user/languages/python/
language: python
python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
install:
  - make setup
script:
  - make test
after_success:
  - make coverage
  - pip install --timeout 120 -q coveralls
  - coveralls

